### ISSUE TITLE
Create new page : placeholder and valid user input

### ISSUE THREAD

**Issue by DirtyF** [jekyll/jekyll-admin#105]
Some UX feedback after testing the creation of a new page: 

* The placeholder when creating a new page is _Filename_, where as for a new post it is a valid example. I would suggest also a valid example here.

* There does not seem to be a validation on what is entered by the user when creating a page (or a post). So I can type "A new file" with spaces and no extension. But if I try to preview that kind of page, it will download the file instead of displaying it.

**Comment by mertkahyaoglu** [comment]
Thanks for the feedback @DirtyF . 

- Yeah, you are right. I should have used a concrete example for other placeholders as well. Thanks for catching it.

- Validating user inputs will certainly be implemented but i don't think it will be in the first pass. For the preview, since front-end dev server and ruby server run on different ports, preview links are not matching. (`localhost:4000` for the api and `localhost:3000` for the front-end). I believe this is working in the production. I will find a way to fix it for the development 👍

**Comment by benbalter** [comment]
@DirtyF this is awesome! Keep the feedback coming! Glad  you were able to get this running locally.

**Comment by mertkahyaoglu** [comment]
@benbalter Should a filename with spaces be allowed (e.g. new file.md)? Does this cause any problem for the back end?

**Comment by benbalter** [comment]
> Should a filename with spaces be allowed (e.g. new file.md)? Does this cause any problem for the back end?

I don't *think* it will cause problems on the back end, but I also don't think we should support them. Since files become URLs, spaces with files names create ugly URLs. Absent a strong use case to the contrary, we should build tools that encourage users to adopt best practices, not any practice they want.

**Comment by DirtyF** [comment]
A better UX could be to create a default filename from the title and slugify it.
So instead of displaying the current behavior, people could create a page without having to worry about the filename.

![create-page](https://cloud.githubusercontent.com/assets/103008/18061305/8e843094-6e22-11e6-8dff-7f3a754e49ef.png)

The filename still can me modified later if needed.

**Comment by benbalter** [comment]
> A better UX could be to create a default filename from the title and slugify it.

We could either do this client side, with a generic slugification algorithm, or could create an API endpoint to use Jekyll's native implementation.

**Comment by mertkahyaoglu** [comment]
> We could either do this client side, with a generic slugification algorithm, or could create an API endpoint to use Jekyll's native implementation.

I believe we can do this client side. I'm assigning this to myself. Soon I will create a PR so we can discuss about it there.
