### ISSUE TITLE
Jekyll Admin pre-release 

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll-admin#136]
If you like to test Jekyll Admin before it's released next week, we'd love your help![1]  

It's easy to get Jekyll Admin installed on an existing site[2]. Here's how:

1. Add the following to you site's Gemfile:

    ```ruby
    gem 'jekyll-admin', group: :jekyll_plugins
    ```

2. Run `bundle install`
3. Run `bundle exec jekyll serve`[3]
4. Open [`localhost:4000/admin`](http://localhost:4000/admin) in your browser
5. Let us know what you think

If you do try the pre-release version of Jekyll Admin, we'd love your feedback. Leave it below, or [open a new issues](https://github.com/jekyll/jekyll-admin/issues/new). Happy Jekylling!

---

[1]: It may be a bit rough around the edges, but it shouldn't break your site (hopefully :smile:).
[2]: Don't have a Jekyll site? Run `jekyll new [site name]` to generate one.
[3]: If you're using the GitHub Pages Gem, and have it in your Gemfile as part of the `:jekyll_plugins` group, you'll wanted to use the command `DISABLE_WHITELIST=true bundle exec jekyll serve` instead.

**Comment by Crunch09** [comment]
@benbalter @mertkahyaoglu Great job! Installation went smooth 🎉

 First thing i noticed  is the warning "You have no title" at the top of the page.

<img width="430" alt="screen shot 2016-08-18 at 22 15 13" src="https://cloud.githubusercontent.com/assets/570608/17789214/6d7e89f6-6591-11e6-988b-5d5fa933fc71.png">

I  guessed but didn't know before looking in the code that i should add a title in my global config. Maybe we could add a hint on what the user should do to set a title as this config option is not documented in the [docs](https://jekyllrb.com/docs/configuration/). Or we could convert it to an input field for a title on click if no title is present?

**Comment by rubenmedios** [comment]
I tried and works fine, i'm waiting for the final release. Yeah!

**Comment by alidcastano** [comment]
+1 just installed it, works great.

Just the other day I was thinking of switching to ghost for a CMS, but I didn't want to sacrifice Jekyll's flexibility. Glad I held on! 

Some thoughts: 

- It'd be more pleasing if there was dashboard main page, or if you landed on `posts`, rather than  being welcomed by `pages` you're likely not going to edit. Though this behavior might be different from me, since I included a `_pages` directory. 
- On fullscreen view, it would be helpful to have a `save` button on the right side of toolbar. You can't really use `cmd+s` on the browser to save changes, and it would be annoying to have to exit fullscreen every time you wanted to save. Plus, the right side is empty, so why not (: 
- If you have unsaved changes and try to leave page, you should be prompted to confirm whether you want to `stay` or `leave`. It'd suck to lose all your progress because you accidently hit the back button.

**Comment by mertkahyaoglu** [comment]
@Crunch09 , @rubenmedios , @alidcastano Thank you guys for your feedback ❤️

**Comment by borisschapira** [comment]
Hi! I tried on my website and when I want to edit a post, the error "Could not find the document" is displayed. I have a lot of configuration for my posts in scopes. Maybe that's the problem.

Reproduction: 

```
git clone git@github.com:borisschapira/borisschapira.com.git test_boris; 
cd test_boris; 
bundle install; 
bundle exec rake;
```

**Comment by frankis** [comment]
Works - thanks!

Findings (apart from "looks pretty & promising!"):

1.  Configuration
- My Configuration within JekyllAdmin dashboard is empty, showing nothing.

2. I am storing any globals outside of _config.yml (e.g. in _data/globals.yml), but JekyllAdmin won´t read the sites Title from there. Do we have to move all globals back to _config.yml or is there an option to tell JekyllAdmin looking for other files as well?

3. Posts & Pages:
- [FrontMatter defaults](https://jekyllrb.com/docs/configuration/#front-matter-defaults) aren´t applied when creating new posts or pages 

4. Pages:
- main.scss appears in the list of pages
- NiceToHave: settings for JekyllAdmin within _config.yml to make specific files, folders, pages, ... hidden in JekyllAdmin

5. Posts:
- "New document" should be "New post"
- Filename placeholder text, as well as syntax check, should reflect and respect the users permalink configuration e.g. "/blog/:year/:month/:day/:title/" or "slug" or any other supported built-in permalink styles
- Posts may be created even though if the filename doesn't match permalink structure (syntax check would be nice here and save time). 
-  A new post may be created even though no layout is applied (post is created in _posts but is not shown in JekyllAdmin - maybe due to invalid FrontMatter)
I would highly recommend making use of "defaults" as mandatory for working with JekyllAdmin and having those settings reflected upon creation of posts and pages.

**Comment by benbalter** [comment]
> Some thoughts:

@alidcastano All three of those are great ideas. Would you mind opening a new issue for each so that that so we can discuss them further and track their progress?

> Hi! I tried on my website and when I want to edit a post, the error "Could not find the document" is displayed. 

@borisschapira the issue is that Jekyll Admin does not current support posts in subfolders. I opened https://github.com/jekyll/jekyll-admin/issues/150 to track fixing that.

> -- My Configuration within JekyllAdmin dashboard is empty, showing nothing.

@frankis do you have a config file? What's it's path relative to the site source?

> I am storing any globals outside of _config.yml (e.g. in _data/globals.yml), but JekyllAdmin won´t read the sites Title from there. Do we have to move all globals back to _config.yml or is there an option to tell JekyllAdmin looking for other files as well?

While there's nothing wrong with doing that for your own site, that's not a design pattern that I've seen widely adopted for Jekyll sites and would recommend putting the title in the config file where other plugins like Jekyll SEO Tag, Jekyll Sitemap, Jekyll Feed, etc. would expect it to be.

>  FrontMatter defaults aren´t applied when creating new posts or pages

Front matter defaults should be *applied*, in that, when the page is rendered via Jekyll, they will be taken into account, but they do not appear as editable fields on the post/page edit screen. What behavior would you expect to see?

> -- main.scss appears in the list of pages

This is the intended, if not unexpected behavior as technically that's a page. Perhaps we should only show pages that render to HTML? 

> -- "New document" should be "New post"

Technically, a post is a document, at least in Jekyll's eyes, but that'd be a good bit of polish to match user expectations.

> -- Filename placeholder text, as well as syntax check, should reflect and respect the users permalink configuration e.g. "/blog/:year/:month/:day/:title/" or "slug" or any other supported built-in permalink styles... Posts may be created even though if the filename doesn't match permalink structure (syntax check would be nice here and save time). 

Could you explain this a bit more? The filename is the filename as it is saved on disk, the permalink is the resulting destination. Would you like the edit screen to show the computed permalink?

> -- A new post may be created even though no layout is applied (post is created in _posts but is not shown in JekyllAdmin - maybe due to invalid FrontMatter)

Can you explain this a bit more? Steps to reproduce would be helpful here.

**Comment by borisschapira** [comment]
Thank you @benbalter!

**Comment by alidcastano** [comment]
@benbalter done!

1) dashboard home page: https://github.com/jekyll/jekyll-admin/issues/156
2) save button on tool-bar: https://github.com/jekyll/jekyll-admin/issues/157
3) confirm before leaving page with unsaved changes: https://github.com/jekyll/jekyll-admin/issues/158

First time submitting feature requests, so let me know if there's anything else I should do. 

Also, I'd be happy to help with any of those changes. Front end part shouldn't be too hard. I just don't know Ruby, and have been focusing on learning node.js, so not sure to what degree I can contribute.

**Comment by trozware** [comment]
Finally got this installed and working although this is not for the faint-hearted, certainly if (like me) they know little about ruby and all the various places where gem files may be installed with various permissions. But after several hours googling and trying options and installing & uninstalling rbenv (which seemed to work as it left ruby 2.3.0 behind in a folder that bundle install agreed to use once rbenv was gone), I got the admin page to appear.

For people who did not have a GemFile before, I found this worked:
```
source 'https://rubygems.org'
gem "jekyll"
gem "jekyll-paginate"
gem 'jekyll-admin', group: :jekyll_plugins
```

Anyway, the web app looks like it will be good but not yet.

The links on the side frequently fail - a refresh of the page usually fixes this. 

Pages lists several files that are in sub-folders but does not show that they are in sub-folders and cannot display them.

Posts shows a blank page - I have 78 posts files in the _posts folder. I tried refreshing and got "You don't have any documents." For test purposes, I created a new document. I was surprised that the file name was not created for me when I entered the title. When I saved, it saved correctly to my _posts folder but still does not appear when I try to show Posts.

Static files offers no view option, just download or upload and upload just puts files at root level even though it displays files from many sub-folders.

Configuration: it could be great to have access to css files, layouts and includes as well as _config.yml

Testing in Chrome instead of Safari, I find that the navigation links now work and that the posts are listed.

Really looking forward to using this when it is ready - great job :-)

**Comment by frankis** [comment]
@benbalter 
Thanks for showing interest and taking care.
I am splitting my thoughts/findings into different "tickets" for better handling on your side.

**Comment by benbalter** [comment]
Version [0.1.0 is out](https://github.com/jekyll/jekyll-admin/releases/tag/v0.1.0). Thanks everyone for their feedback and congrats to @mertkahyaoglu on a solid 🚢!

**Comment by mertkahyaoglu** [comment]
And big thanks to my dear mentors @benbalter, @parkr and @jldec  🎉
