### ISSUE TITLE
Link theme files via JekyllAdmin interface

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/jekyll-admin#209]
I request to have theme files linked via JekyllAdmin.

Say, I have a blog setup with Jekyll 3.2.1 on Windows
In order to change the stylesheets or layouts or even a minor change to one of the includes, I've to open another Explorer window and navigate to my gems folder and then jump back-and-forth between the various directories as I change things around. Novice user or advanced, this is quite irritating.

Now that Jekyll sports a UI, it should automatically show theme files ( and be able to edit them ). Syntax-highlighting is a plus, not necessary, at the moment.

Thanks :smiley:

**Comment by benbalter** [comment]
@ashmaroli thanks for the suggestion. For context, when @mertkahyaoglu and I were originally specing out the project, we purposely placed theme/layout editing out of scope for three reasons:

1. The problem we were trying to solve was authoring and managing *content*, and we wanted to focus on the content editing interface, so that we could make it awesome.

2. Editing a layout is very different than editing a markdown file. While it's easy to add a Markdown editor to a view, there are many purpose-built tools out there that do a much better job at editing HTML (e.g. Atom).

3. The type of user that could most benefit from Jekyll Admin, are those that don't want to edit themes or layouts. They just want to edit content. Those interested in editing layouts are generally more advanced users, and can be expected to install a dedicated text editor, which will be better suited for the task.

**Comment by ashmaroli** [comment]
@benbalter, okay. the initial scope excluded themes on purpose. I get that.
Can the scope be extended, and have this FR under consideration for the near future? :smiley:

**Comment by DirtyF** [comment]
I'd rather see the project focus on enhancing the writing user experience (think keyboard shortcuts, better typography for instance, customizing editor to your needs) than trying to mimic Wordpress and clutter the UI. [Removing a feature is a feature](http://ben.balter.com/2016/07/21/removing-a-feature-is-a-feature/).

**Comment by mertkahyaoglu** [comment]
Agree with @DirtyF , @benbalter. Sorry took so long 😬
