### ISSUE TITLE
Document object should include unrendered markdown content

### ISSUE THREAD

**Issue by mertkahyaoglu** [jekyll/jekyll-admin#35]
I can fetch the all post documents. This is the result; (I added the `title` attribute to the front matter)

![screen shot 2016-07-09 at 5 43 41 pm](https://cloud.githubusercontent.com/assets/7414026/16708450/03f653a0-45fd-11e6-9fdc-b5003dbda494.png)

As you see, the response includes the document body (in html format but we have a markdown editor in the front-end).
Did we eliminate the `GET /collections/:collection_name/documents/:id`? Because I'm not able to fetch the post with id `/2016/01/01/test`. Although it is pointless since we have everything we need, I think.

**Comment by benbalter** [comment]
@parkr any clean way to get the pre-rendered HTML with `to_liquid`? Shouldn't that be the difference between `output` and `content`?

> Did we eliminate the `GET /collections/:collection_name/documents/:id`? Because I'm not able to fetch the post with id `/2016/01/01/test`

I ran `script/test-server` (pro-tip, at least in Chrome, you can go to `/_api` and click through the resources if you have [this extension](https://chrome.google.com/webstore/detail/json-formatter/bcjindcccaagfpapjjmafapmmgkkhgoa?hl=en) installed), and was able to access `GET http://localhost:4000/_api/collections/posts/2016-01-01-test.md`.

I think `/collections/posts/2016-01-01-test.md` makes more sense than `/collections/posts/documents/2016-01-01-test.md`, with the logic being that the posts are the documents, thus it's a duplicative namespace, but it's an easy enough change if you believe otherwise.

**Comment by mertkahyaoglu** [comment]
@benbalter Currently `id` is in `/2016/01/01/test` format. Is there a way for server to change it to `2016-01-01-test.md` ? Or should front-end make the conversion itself?

> I think /collections/posts/2016-01-01-test.md makes more sense

I agree, this one is simple and better.

**Comment by benbalter** [comment]
> Is there a way for server to change it to 2016-01-01-test.md

Yes. Opened https://github.com/jekyll/jekyll-admin/issues/41 to track.

**Comment by parkr** [comment]
> @parkr any clean way to get the pre-rendered HTML with to_liquid? Shouldn't that be the difference between output and content?

No, for historical reasons `output` and `content` are the same at the end of a build. There is no way to get the raw content. See https://github.com/jekyll/jekyll/pull/2901 for more. [The code that does it](https://github.com/jekyll/jekyll/blob/d4a7fbee28323576c88bbc4b4d689d267389dc47/lib/jekyll/renderer.rb#L67).
