### ISSUE TITLE
"New metadata field" should switch focus to newly created field

### ISSUE THREAD

**Issue by mariusa** [jekyll/jekyll-admin#400]
After clicking on New metadata field and adding the field, please focus the cursor in the newly created field (which should be empty, not "New field 3"), so one can directly start entering the name instead of mouse clicking & selecting.

**Comment by danielbastos11** [comment]
Seems pretty straightforward to implement, imo.
We'd just need to flag the newly created input and set the autofocus HTML5 attribute on render based on the flag.

If there's consent to implement it, I'll do it asap and create a pull request.

**Comment by mertkahyaoglu** [comment]
@danielbastos11 I would love that 👍  Early in the project, I tried to implement this but I don't remember what kept me away 😬  Would love to help you with that.

**Comment by ashmaroli** [comment]
> We'd just need to flag the newly created input and set the autofocus HTML5 attribute on render based on the flag.

Not so sure if that's gonna work or if would necessitate an extra step to have the attribute disabled when the next new field is created, I was hoping to find the use of javascript `.focus()`..

But that said, don't let me get in your way.. :grimacing:

**Comment by danielbastos11** [comment]
@ashmaroli I see what you mean, but that shouldn't be a problem. Redux will change the state when the next new field is created, causing the component's `render()` function to be reinvoked, which will lead to the `autofocus` attribute being removed or inserted as needed.

Using `.focus()` instead of of `autofocus` has its pros and cons. The browser support for `autofocus` ain't that great (see [this](http://caniuse.com/#feat=autofocus)), but using `.focus()` would be a break from the functional paradigm, which is always bad when working with React.

**Comment by danielbastos11** [comment]
I pushed something to a [branch](https://github.com/danielbastos11/jekyll-admin/tree/newFieldFocus) on my fork.

Instead of flagging the new field, I create it with a empty field for a key, and assume that the field with an empty key is new and therefore should be focused.

I went with `.focus()` instead of `autofocus` because the component was using refs already, so there was no point in being purist.

The downside to my approach is that the new field is created with black key and value - but that should be easy to fix.

**Comment by mertkahyaoglu** [comment]
What about this idea?

We have `new_field_count` key in the [store](https://github.com/jekyll/jekyll-admin/blob/master/src/reducers/metadata.js#L14) which keeps track of the last metadata key created. We use this key to name our new keys uniquely (e.g. New key 3). Since we know the index of the last created key, we can add autofocus prop to the next input element which will be created with that key plus 1.

To be able to do this, we will need to pass this `new_field_count` key down to `MetaField` component.

**Comment by mariusa** [comment]
@mertkahyaoglu That sounds error prone.

Not sure where the complexity comes from. In backbone, after inserting the metafield group in DOM, one would do
this.$(".metafield input.key-field").focus() 

assuming "this" is the  the metafield group (key + value)

**Comment by danielbastos11** [comment]
@mariusa We could do this in React, but we shouldn't. React is all about functional programming, with components acting as pure functions that take props and states as arguments and return a view. While doing things like `this.$(".metafield input").focus()` is possible through the Refs API, it should be avoided.

**Comment by danielbastos11** [comment]
@mertkahyaoglu Seems like a good ideia! 

Just a question for everybody: why would we need multiple new fields? Shouldn't it be a boolean kind of thing? Either you have a field under construction or you don't, right? So, if I'm right, couldn't we just have a flag to determine if we have a new field and then render a blank input that always take focus if the flag resolves to true?

**Comment by ashmaroli** [comment]
Perhaps I got a little too comfortable with current setup, but I like the logical flow of how the `Metafield` component renders now.  The parent container `Metafields` take the metadata object as props and *stores* data internally using the pre-existing keys. When a *new-field* is created, the metadata object gets extended with the new key and a blank-value:
```javascript
// in my head.. so conventional syntax not required.. ;)

var metadata = props.metadata
('.add-new').onClick => metadata += metadata['new_field_*']
```
The above is simple for even a newbie like me to grasp.. no flags.. no shenanigans..
But perhaps that is also the reason why I'm stumped when attempting to reach a simple solution.

**Comment by mertkahyaoglu** [comment]
Created a PR for this (#410). What do you guys think about it?

**Comment by danielbastos11** [comment]
Sorry for the really late reply, but the PR looks great!

Btw, I had some ideas for the metadata part of the app, and I'll be opening a new issue to share it as soon as I can.

Great job, guys!
