### ISSUE TITLE
Show current page title in browser tab, instead of "Jekyll Admin"

### ISSUE THREAD

**Issue by mariusa** [jekyll/jekyll-admin#401]
The icon is enough to identify that tab is for "Jekyll Admin".
We're editing multiple pages in multiple tabs, and having the actual page title instead of "Jekyll Admin" in browser tabs would help identify them.

Thanks

**Comment by ashmaroli** [comment]
I did consider implementing this in the past but left it due to lack of clarity in what could be the best solution:

 - Should it reflect `title` or would `relative_path` be better?
 - Should it be `page['title']` or `Jekyll Admin | page['title']` or `site['title'] | page['title']`
 - Centralized implementation (how?) or modify individual `views`

**Comment by mertkahyaoglu** [comment]
@ashmaroli Does it matter ?

Since Jekyll Admin runs locally which means SEO is not a think to care about, one should be enough just to distinguish tabs. Therefore, I think `page['title']` would be sufficient.

I assume the solution will be related with `react-router` as the frontend is a single page app.

**Comment by ashmaroli** [comment]
Two candidates:
  - [react-document-title](https://github.com/gaearon/react-document-title)
    - Popular
    - Regularly updated
    - Declarative -- would require updating every view page
    - might be an overkill IMO
  - [redux-title](https://github.com/DJCordhose/redux-title)
    - not-so-popular
    - last commit: Oct 2016
    - supposedly syncs with redux state -- may work with our existing `metadata` reducer
    - might be enough for us.

Thoughts?

**Comment by mertkahyaoglu** [comment]
👍  for `react-document-title` for the reason you listed and also for the author 💯  I will integrate this when I get a chance.
