### ISSUE TITLE
Should front-end remove `dist` folder on prestart?

### ISSUE THREAD

**Issue by mertkahyaoglu** [jekyll/jekyll-admin#87]
After #86, front-end will be built on each start. This happens because it removes `dist` folder before starting ([here](https://github.com/jekyll/jekyll-admin/blob/master/lib/jekyll-admin/public/package.json#L7)). After that it starts `test-server` and building process starts. 

Since `npm start` commands, [here](https://github.com/jekyll/jekyll-admin/blob/master/lib/jekyll-admin/public/package.json#L8), runs in parallel, development server most likely will start before `test-server `and front-end won't be able to show the contents until `test-server` is ready. What can we do about this?

**Options;**

* Do not run start commands in parallel.
* Do not remove dist folder before starting.

**Comment by benbalter** [comment]
> runs in parallel

@mertkahyaoglu to clarify, you're worried about a race condition between the ruby tests begining before the node tests have built the front end?

If that's the case, I believe we should be fine. Node runs the two tests on two separate boxes, meaning there's no risk of filesystem clash (and the ruby test simply stubs the `dist` folder to ensure its contents are served).

**Comment by mertkahyaoglu** [comment]
Actually the front-end begins before the api. Therefore, it shows no pages/documents/config. If you run the `server-frontend` script, you will see it clearly.

**Comment by benbalter** [comment]
Gotcha. To summarize:

* `script/server-frontend` spawns `script/test-server` (the API) and then runs its build process
* `script/test-server` checks if `dist` exists and if not, compiles front end
* When `dist` doesn't exist, there's a race condition, and the front end server may load before the API responds (due to the time it takes to compile the front end).

To resolve this, we could:

* Pass a flag to `script/test-server` to skip the build process
* Not build the compiled site, unless asked, and fail with a descriptive error message

I think I like the second option better, because it removes complexity, rather than adds it, and that makes the primary means of testing `script/server-frontend`, which makes more sense.

I'll get a PR together that doesn't compile the site unless asked, which should resolve the race condition.

**Comment by mertkahyaoglu** [comment]
Thank you @benbalter 👍
